CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL , 
    [Source] VARCHAR(50) NOT NULL, 
    [Tag] VARCHAR(50) NULL, 
    [Extension] VARCHAR(50) NULL, 
    [OverviewPosition] VARCHAR(50) NULL, 
    [Site] VARCHAR(50) NULL, 
    [Plant] VARCHAR(50) NULL, 
    [Equipment] VARCHAR(50) NULL, 
    [Model] VARCHAR(50) NULL, 
    [Unit] VARCHAR(50) NULL, 
    [TagComment] VARCHAR(MAX) NULL, 
    [AlarmPriorityOriginal] VARCHAR(50) NULL, 
    [AlarmPriorityModified] VARCHAR(50) NULL, 
    [TagMarkColorOriginal] VARCHAR(50) NULL, 
    [TagMarkColorModified] VARCHAR(50) NULL,
	[Detection] VARCHAR(50) NULL, 
    [Purpose] VARCHAR(50) NULL, 
    [Consequence] VARCHAR(50) NULL, 
    [Time-to-respond] VARCHAR(50) NULL, 
    [Guidance] VARCHAR(50) NULL, 
    [AutoClear] VARCHAR(50) NULL, 
    [MonitoringDeniedUser] VARCHAR(50) NULL, 
    [MonitoringDeniedUserGroup] VARCHAR(50) NULL, 
    [AcknowledgementDeniedUser] VARCHAR(50) NULL, 
    [AcknowledgementDeniedUserGroup] VARCHAR(50) NULL, 
    [ManualResetPermittedUser] VARCHAR(50) NULL, 
    [ManualResetPermittedUserGroup] VARCHAR(50) NULL, 
    [ManualResetDeniedUser] VARCHAR(50) NULL, 
    [ManualResetDeniedUserGroup] VARCHAR(50) NULL, 
    [AlarmGroup] VARCHAR(50) NULL, 
    [Shelving] VARCHAR(50) NULL, 
    [AlarmSetpointLowLimit] VARCHAR(50) NULL, 
    [AlarmSetpointHighLimit] VARCHAR(50) NULL, 
    [AlarmSetpointMaster] VARCHAR(50) NULL, 
    [ProjectID] VARCHAR(50) NULL, 
    PRIMARY KEY ([Id]),
)
